# Generated by Django 3.2 on 2023-01-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=20)),
                ('adhar_number', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
            ],
        ),
    ]
