# Generated by Django 3.2 on 2023-01-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('front', models.FileField(upload_to='front')),
                ('back', models.FileField(upload_to='back')),
            ],
        ),
    ]
