# Generated by Django 3.2 on 2023-01-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagedata', '0002_auto_20230109_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
