# Generated by Django 3.2 on 2023-01-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagedata', '0003_auto_20230104_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
