# Generated by Django 3.2 on 2023-01-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagedata', '0003_auto_20230109_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
