# Generated by Django 3.2 on 2023-01-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagedata', '0004_auto_20230111_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhardata',
            name='yob',
        ),
    ]
