# Generated by Django 3.2 on 2023-01-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagedata', '0004_usertable_is_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhaar',
            name='address',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
