# Generated by Django 3.2 on 2023-01-06 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagedata', '0007_auto_20230106_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhardata',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imagedata.userprofile'),
        ),
        migrations.AlterField(
            model_name='aadharimage',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imagedata.userprofile'),
        ),
    ]
