# Generated by Django 3.2 on 2023-01-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagedata', '0008_rename_adhar_number_userprofile_aadhaar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhardata',
            name='is_adhar_matched',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='aadhardata',
            name='is_dob_matched',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='aadhardata',
            name='is_name_matched',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='aadhardata',
            name='is_pincode_matched',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='aadhardata',
            name='is_sex_matched',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
