# Generated by Django 3.2 on 2023-01-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagedata', '0009_auto_20230112_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
